CFLAGS = /nologo /W3 /EHsc

objs = run_test.obj  test1.obj test2.obj test3.obj \
	test4.obj test5.obj test6.obj test7.obj test8.obj test9.obj

all: $(objs)

run_test.obj: run_test.c
test1.obj: test1.c
test2.obj: test2.c
test3.obj: test3.c
test4.obj: test4.c
test5.obj: test5.c
test6.obj: test6.c
test7.obj: test7.c
test8.obj: test8.c
test9.obj: test9.c

clean:
	del /Q /S $(objs) run_test.exe *~
